In [1]:
#word embeding

In [2]:
#import some libraries
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
#dataset of the sentences
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understand the meaning of words",
      "your videos are good",]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
#DEFINE VOCAB SIZE
voc_size=10000

In [6]:
#define the one hot representation of the sentences
one_hot_repre=[one_hot(words,voc_size) for words in sent]
one_hot_repre

[[7101, 6695, 9264, 7593],
 [7101, 6695, 9264, 9604],
 [7101, 7803, 9264, 4669],
 [346, 7531, 7755, 5224, 367],
 [346, 7531, 7755, 5224, 1581],
 [8115, 7101, 9395, 9264, 7326],
 [8680, 3631, 32, 5224]]

In [7]:
#WORD EMBEDDING REPRESENTATION

In [9]:
#import the library for word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [23]:
#set the embedding vector features
sent_length=8

embedded_docs=pad_sequences(one_hot_repre,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7101 6695 9264 7593]
 [   0    0    0    0 7101 6695 9264 9604]
 [   0    0    0    0 7101 7803 9264 4669]
 [   0    0    0  346 7531 7755 5224  367]
 [   0    0    0  346 7531 7755 5224 1581]
 [   0    0    0 8115 7101 9395 9264 7326]
 [   0    0    0    0 8680 3631   32 5224]]


In [15]:
#set the dimension
dim=10

In [16]:
#now build the model for word embedding
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mae")


c:\Users\Ashitosh Shirsath\Desktop\ASH G AI\NLP\tfenv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 7101, 6695, 9264, 7593], dtype=int32)

In [21]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[ 0.03729018,  0.04598333, -0.01970236,  0.02248961,  0.01720882,
         0.02403222, -0.00036553, -0.0409543 , -0.01776171, -0.00758598],
       [ 0.03729018,  0.04598333, -0.01970236,  0.02248961,  0.01720882,
         0.02403222, -0.00036553, -0.0409543 , -0.01776171, -0.00758598],
       [ 0.03729018,  0.04598333, -0.01970236,  0.02248961,  0.01720882,
         0.02403222, -0.00036553, -0.0409543 , -0.01776171, -0.00758598],
       [ 0.03729018,  0.04598333, -0.01970236,  0.02248961,  0.01720882,
         0.02403222, -0.00036553, -0.0409543 , -0.01776171, -0.00758598],
       [ 0.00605048, -0.04998159,  0.03470403,  0.01082417,  0.02209253,
        -0.00278134, -0.03646559,  0.04775927, -0.03092059,  0.00955511],
       [-0.02310469,  0.0490909 ,  0.04573932,  0.01564207,  0.00792242,
        -0.03545847, -0.03946399, -0.02609405,  0.00759929,  0.03241868],
       [-0.02438012,  0.03167986, -0.04156382, -0.02981753,  0.01273969,
        -0.0068674 , -0.03691825, -0.0015812 